### ISSUE TITLE
可以编译一个ARM32位系统的tpclash吗

### ISSUE THREAD

**Issue by ChiehJang** [QingNetwork/tpclash#8]
目前使用玩客云 ，现在已经刷成armbian 32位系统。

tpclash 64位arm无法在此设备运行。
```
root@aml-s812:~# bash clash
clash: clash: cannot execute binary file
root@aml-s812:~# file clash 
clash: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=3JkJUObF8x3A6T5xhekq/7TnYfBNmTccyOwt1lm82/Qu_H6rdPI9nXmLAip8Xh/BOGqh1Tf78QlSU7xJykU, stripped
root@aml-s812:~#  uname -m 
armv7l
```

**Comment by j33h22** [comment]
Dear [ChiehJang](https://github.com/ChiehJang),
  Your issue i am noticed. So I compile different of arm platform for you
  Hope you can continue Support this project.

Ju33Huang22
Best regards.

https://github.com/QingNetwork/tpclash/releases/tag/v0.1.20

**Comment by ChiehJang** [comment]
You’re very kind & hansome!!!❤
